/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CredentialRegistryInterface extends Interface {
    getFunction(nameOrSignature: "getPatientRecordAt" | "getPatientRecordCount" | "getRecordById" | "issueRecord" | "verifyRecord"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RecordIssued"): EventFragment;

    encodeFunctionData(functionFragment: 'getPatientRecordAt', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPatientRecordCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRecordById', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'issueRecord', values: [AddressLike, string, BytesLike, string]): string;
encodeFunctionData(functionFragment: 'verifyRecord', values: [BigNumberish, string, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'getPatientRecordAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPatientRecordCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRecordById', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issueRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyRecord', data: BytesLike): Result;
  }

  
    export namespace RecordIssuedEvent {
      export type InputTuple = [recordId: BigNumberish, issuer: AddressLike, patient: AddressLike, cid: string, payloadHash: BytesLike, credentialType: string, issuedAt: BigNumberish];
      export type OutputTuple = [recordId: bigint, issuer: string, patient: string, cid: string, payloadHash: string, credentialType: string, issuedAt: bigint];
      export interface OutputObject {recordId: bigint, issuer: string, patient: string, cid: string, payloadHash: string, credentialType: string, issuedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CredentialRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): CredentialRegistry;
    waitForDeployment(): Promise<this>;

    interface: CredentialRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getPatientRecordAt: TypedContractMethod<
      [patient: AddressLike, index: BigNumberish, ],
      [[bigint, string, string, string, string, string, bigint] & {recordId: bigint, issuer: string, subject: string, cid: string, payloadHash: string, credentialType: string, issuedAt: bigint }],
      'view'
    >
    

    
    getPatientRecordCount: TypedContractMethod<
      [patient: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getRecordById: TypedContractMethod<
      [recordId: BigNumberish, ],
      [[string, string, string, string, string, bigint] & {issuer: string, patient: string, cid: string, payloadHash: string, credentialType: string, issuedAt: bigint }],
      'view'
    >
    

    
    issueRecord: TypedContractMethod<
      [patient: AddressLike, cid: string, payloadHash: BytesLike, credentialType: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    verifyRecord: TypedContractMethod<
      [recordId: BigNumberish, cid: string, payloadHash: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getPatientRecordAt'): TypedContractMethod<
      [patient: AddressLike, index: BigNumberish, ],
      [[bigint, string, string, string, string, string, bigint] & {recordId: bigint, issuer: string, subject: string, cid: string, payloadHash: string, credentialType: string, issuedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getPatientRecordCount'): TypedContractMethod<
      [patient: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRecordById'): TypedContractMethod<
      [recordId: BigNumberish, ],
      [[string, string, string, string, string, bigint] & {issuer: string, patient: string, cid: string, payloadHash: string, credentialType: string, issuedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'issueRecord'): TypedContractMethod<
      [patient: AddressLike, cid: string, payloadHash: BytesLike, credentialType: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyRecord'): TypedContractMethod<
      [recordId: BigNumberish, cid: string, payloadHash: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'RecordIssued'): TypedContractEvent<RecordIssuedEvent.InputTuple, RecordIssuedEvent.OutputTuple, RecordIssuedEvent.OutputObject>;

    filters: {
      
      'RecordIssued(uint256,address,address,string,bytes32,string,uint256)': TypedContractEvent<RecordIssuedEvent.InputTuple, RecordIssuedEvent.OutputTuple, RecordIssuedEvent.OutputObject>;
      RecordIssued: TypedContractEvent<RecordIssuedEvent.InputTuple, RecordIssuedEvent.OutputTuple, RecordIssuedEvent.OutputObject>;
    
    };
  }